Repository openstack-exporter/openstack-exporter, pull requests merged in 2020-12, with the labels that each got.

#145 add metric free_disk_bytes for hypervisors
  README.md
  exporters/nova.go
  exporters/nova_test.go
Labels: new-metrics

#141 Add support for multiple clouds
  Makefile.common
  README.md
  exporters/exporter.go
  main.go
Labels: feature-request

#143 Reduce cardinality of Cinder volume status metrics
  README.md
  exporters/cinder.go
  exporters/cinder_test.go
Labels: new-metrics

#149 Add limits values for instances
  README.md
  exporters/nova.go
  exporters/nova_test.go
Labels: new-metrics

#147 Bind a exporter to only needed tcp version
  exporters/utils.go
  main.go
Labels: bug

#150 fixes #122
  exporters/cinder_test.go
  exporters/containerinfra_test.go
  exporters/designate_test.go
  exporters/exporter.go
  exporters/glance_test.go
  exporters/gnocchi_test.go
  exporters/ironic_test.go
  exporters/keystone_test.go
  exporters/neutron_test.go
  exporters/nova_test.go
Labels: bug
