Repository openstack-exporter/openstack-exporter, pull requests merged in 2020-07, with the labels that each got.

#103 Metrics for Designate
  README.md
  exporters/designate.go
  exporters/designate_test.go
  exporters/exporter.go
  exporters/exporter_test.go
  exporters/fixtures/designate_recordsets.json
  exporters/fixtures/designate_zones.json
  exporters/fixtures/tokens.json
  main.go
Labels: enhancement, new-metrics

#109 Fix dns metrics for all projects
  README.md
  exporters/designate.go
  exporters/designate_test.go
Labels: bug

#113 Add Ironic node state exporter
  README.md
  exporters/exporter.go
  exporters/exporter_test.go
  exporters/fixtures/ironic_nodes.json
  exporters/fixtures/tokens.json
  exporters/ironic.go
  exporters/ironic_test.go
  exporters/utils.go
  main.go
Labels: new-metrics
